# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev50+g527fe3f.d20240902'
__version_tuple__ = version_tuple = (0, 1, 'dev50', 'g527fe3f.d20240902')
